Homework2
made-ml-in-prod-2021/mrtimmy89 pull request #3
Opened 2021-05-19 13:17 UTC by MrTimmy89

Злравствуйте!<br><br>То, что было выполнено в рамках задания детально описано в README.md. Добавлю от себя, после запуска образа при в целом корректной работе и отображении соответствующего статуса **(INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit))** в том же десктопном варианте Docker, выполнить **make_request.py** не вышло, программа выдает ошибку **(requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /predict/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x181567D8
 \>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))** . При этом работа через стандартный локальный запуск **uvicorn app:app --reload** срабатывает корректно.<br>Из мелочей:
- были удалены части проекта, отвечающие за обучение модели
- был добавлен кусок кода, отвечающий за генерацию имен файлов с предсказаниями, учитывающий локальное время системы.<br><br>Заранее спасибо за фидбэк!

2021-05-19 13:20 UTC, MrTimmy89 commented
Added a forgotten hw2 label

2021-05-19 19:26 UTC, LKudrenok reviewed
1. "выполнить make_request.py не вышло, программа выдает ошибку (requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded" - судя во всему, у тебя был запущен сервис, а потом ты попытался на этом же порту запустить контейнер, поэтому и такая ошибка.

2. Советую использовать .gitignore, чтобы не трекать/пушить __pycache__ файлы.

3. В тестах есть тесты на то, запущен ли сервис ("/"), и на использование модели (predict_model), а вот теста на работу "/predict" нет.

2021-05-19 19:26 UTC, LKudrenok commented on online_inference/make_request.py
> +    )
Надежнее использовать os.path.join (или что-нибудь из pathlib), чтобы не париться насчет слэшей.
И обычно для форматирования вывода даты-времени используется datetime.strftime(), но, возможно, в данном случае re.sub и поудобнее будет

2021-05-19 19:26 UTC, LKudrenok commented on online_inference/src/features/make_features.py
> +    return df.columns.tolist()
Можно упростить
```
if "target" in df.columns:
    df.drop('target', axis=1, inplace=True)
return df.columns.tolist()
```

2021-05-19 19:26 UTC, LKudrenok commented on online_inference/src/data/preprocess_data.py
> +df = pd.read_csv(SOURCE_FILEPATH, index_col=["age"])
Не очень понятно, зачем делать одну из фич (age) индексом

2021-05-23 13:01 UTC, Mikhail-M requested changes
удалите пожалуйте .pyc

лучше прописать в gitignore

2021-05-27 08:32 UTC, Mikhail-M commented
по поводу не вышло обратиться

запускать надо с docker run -p LOCAL_PORT:REMOTE_PORT

2021-05-27 08:34 UTC, Mikhail-M reviewed
Плоховато, что скопирована большая часть кода с прошлого ДЗ. Это 2 разных проекта и пересечение кода должно быть поменьше. 

Оптимизация: 1.5(что нужно на полный балл, было в дискорде вчера)
Тесты: 2 , хорошо бы, чтобы модель готовилась в фикстуре или мокалось ее ожидаемые ответы)

Баллы: 16.5

2021-05-27 08:35 UTC, Mikhail-M approved these changes
Плоховато, что скопирована большая часть кода с прошлого ДЗ. Это 2 разных проекта и пересечение кода должно быть поменьше.

Оптимизация: 1.5(что нужно на полный балл, было в дискорде вчера)
Тесты: 2 , хорошо бы, чтобы модель готовилась в фикстуре или мокалось ее ожидаемые ответы)

Баллы: 16.5

2021-05-27 10:10 UTC, MrTimmy89 commented
Спасибо!

2021-05-27 10:10 UTC, merged