Homework3
made-ml-in-prod-2021/mrtimmy89 pull request #4
Opened 2021-06-04 15:53 UTC by MrTimmy89

Добрый вечер!<br>
В PR airflow проект, в приложении принтскрины работы DAGs при развертывании через docker-compose up --build.
По принтсвринам - все довольно очевидны. Поясню за два) prerequisits - добавление  нового "connection" типа "file" fs_default для успешной работы Sensors, for_predictions - описанное в readme создание папки и input.csv для хранения файлов, на основании которых модель ежедневно делает предсказания.<br><br>
По поводу тестов. На основании BestPrectices был написан test_DAG.py. Запустить его под Windows не получилось, хотя по логике все должно быть верно.

2021-06-05 15:12 UTC, bulaevvi requested changes
В проекте не приложены скриншоты с Airflow, необходимо добавить для соответствия формальным критериям

2021-06-05 15:12 UTC, bulaevvi commented on airflow_ml_dags/README.md
> +<br><br>
Необходимо добавить команду для остановки сервиса Ctrl+C

2021-06-05 15:12 UTC, bulaevvi commented on airflow_ml_dags/images/airflow-split/split.py
> +
Наверно стоит специфицировать random_state для воспроизводимости

2021-06-05 15:12 UTC, bulaevvi commented on airflow_ml_dags/images/airflow-train/train.py
> +    dataframe = pd.read_csv(os.path.join(train_path, "train.csv"), index_col=0)
В параметрах классификатора стоит прописать параметр random_state для воспроизводимости результатов

2021-06-05 15:12 UTC, bulaevvi commented on airflow_ml_dags/images/airflow-validate/validate.py
> +    roc_auc = roc_auc_score(y_val, prediction)
Хороший набор метрик для оценки качества :)

2021-06-05 15:14 UTC, bulaevvi commented
В readme.md необходимо указать команду для запуска тестов

2021-06-06 07:23 UTC, bulaevvi approved these changes

2021-06-06 07:28 UTC, bulaevvi commented
> В PR airflow проект, в приложении принтскрины работы DAGs при развертывании через docker-compose up --build.
> По принтсвринам - все довольно очевидны. Поясню за два) prerequisits - добавление нового "connection" типа "file" fs_default для успешной работы Sensors, for_predictions - описанное в readme создание папки и input.csv для хранения файлов, на основании которых модель ежедневно делает предсказания.

Нашел более простой способ работы с  "connection": в файле docker-compose.yml в разделе init.command добавить строчку ```&& airflow connections add fs_default --conn-type fs```. Тогда connection будет автоматически прописываться при поднятии системы и сенсоры сразу будут работать нормально.

> По поводу тестов. На основании BestPrectices был написан test_DAG.py. Запустить его под Windows не получилось, хотя по логике все должно быть верно.

У меня тоже Win10, я не смог запустить их при проверке PR

2021-06-06 07:33 UTC, bulaevvi commented
В целом работа понравилась, все просто и понятно, ничего лишнего. Локально у меня все запустилось с первого раза, самооценка проведена адекватно.

2021-06-12 12:53 UTC, Mikhail-M commented on airflow_ml_dags/dags/2_predict_DAG.py
> +                '--scaler-path /data/models/{{ ds }} --model-path /data/models/{{ ds }}',
вот здесь по условиям ДЗ нужно использовать модель, не по дате, а из VARIABLES

2021-06-12 12:54 UTC, Mikhail-M commented on airflow_ml_dags/tests/test_DAG.py
> +start >> load >> preprocess >> split >> train >> validate >> [check_scaler, check_model, check_metrics] >> finish
Это здесь зачем?

2021-06-16 13:41 UTC, Mikhail-M commented on airflow_ml_dags/dags/2_predict_DAG.py
> +model = Variable.get('model_dir')
Так лучше не делать
https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#variables

2021-06-16 13:41 UTC, Mikhail-M approved these changes
Тесты: 2.5

Баллы 34.5

2021-06-26 09:25 UTC, merged